### ISSUE TITLE
error in swoole table

### ISSUE THREAD

**Issue by Azare77** [erfanmola/TDXLib#1]
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /*/telegram_bot/vendor/erfanmola/tdxlib/TDXLib.php:608

**Comment by erfanmola** [comment]
سلام وقت‌بخیر، از این متد داخل محیطی استفاده کردید که OpenSwoole در اون نصب هست، ولی خارج از کوروتین کال‌کردید متد IsUserFlooding رو؟
